Dockerfile, Makefile
I uploaded a Dockerfile to reproduce locally the `api.zip` file used by the lambda function. To run it locally, you need to use: 
- `make init_api_docker` to initialize the Docker image.
- `make create_api_zip route=tsfeatures` to create the `api.zip` file for the `tsfeatures` service. `tsfeatures` can be changed for the other services.
=> add local api generation

action_files/create_readme_docs.sh, action_files/create_sdk_reference.py, action_files/modify_markdown.py
This PR:
- Puts tutorials under the `Python SDK` section in readme.com.
- Adds the `SDK Reference` link automatically at the end of the list.
=> [FIX] Add new order to docs hosted in readme.com

.github/workflows/build-docs.yaml, .gitmodules
Adds the action that builds the mintlify docs and pushes them to the docs branch on every push to main along with the scripts needed to create them.
=> add docs scripts

.github/workflows/build-docs.yaml, .gitmodules
`.ferignore` has problems ignoring `docs-scripts` since it is a submodule. See #150. This PR moves `docs-scripts` to `action_files` to be ignored by fern.
=> [FIX] mv docs-scripts to action_files

.github/workflows/build-docs.yaml, .gitmodules
Changes the process to build the docs from using a submodule to cloning the repo.
=> checkout docs repo instead of using submodule

nbs/timegpt.ipynb, nixtlats/timegpt.py
Before this PR, `tenacity` was invoked when errors different than `ApiError` from `httpx` were raised. However, when the endpoint is momentarily unavailable, the client often raises an `ApiError` with a text body.  See:
https://github.com/Nixtla/nixtla/blob/1e2e632de98ee079286f1bcf77c8a07a99f8c65a/nixtlats/client.py#L229
This behavior can be used as a proxy for the unavailability of the endpoint. If the endpoint is available but has a server error, the endpoint should return a JSON-decodable response, and a text response otherwise.
This approach was implemented in this PR and tested with a couple of tests ensuring retrying with a response of [this kind](https://github.com/Nixtla/nixtla/actions/runs/6791773732/job/18463888068#step:5:173) and providing no retrying when the server responds …
=> [FIX] Filter API errors

experiments/lag-llama/Makefile, experiments/lag-llama/README.md, experiments/lag-llama/environment.yml, experiments/lag-llama/src/lag_llama_pipeline.py, experiments/lag-llama/src/main.py, experiments/lag-llama/src/statsforecast_pipeline.py, experiments/lag-llama/src/utils.py
this pr adds an experiment comparing LagLlama against SeasonalNaive on more than 100k time series.
=> feat: add lag-llama experiment

environment.yml
Sets an upper bound on pandas while https://github.com/ray-project/ray/issues/42842 is fixed.
=> set upper bound on pandas

action_files/readme_com/create_readme_docs.sh, nbs/docs/capabilities/000_capabilities.ipynb, nbs/mint.json
- Mintlify prefixes removed in mint.json as apparently mintlify removes the prefix from a filename (?)
- Readme.com file dirs - apparently readme.com gives an error if there is no placeholder notebook in the capabilities folder. This was not the case in the test branch, though. Adding it renders the docs properly again.
=> [FIX] Mintlify prefixes, readme file dirs

setup.py
some [ci/cd tests](https://github.com/Nixtla/nixtla/actions/runs/8954169466/job/24593482500?pr=335) were failing due to this missing dep in `nbs/docs/tutorials/13_bounded_forecasts.ipynb`
=> fix: add pyreadr as dev dep

.github/workflows/ci.yaml
recent docs changes, made the current file glob unusable for skipping distributed tutorials on some operating systems. this pr fixes the problem.
=> fix: update distributed to computing at scale

nbs/docs/use-cases/1_forecasting_web_traffic.ipynb, nbs/docs/use-cases/2_bitcoin_price_prediction.ipynb, nbs/docs/use-cases/3_electricity_demand.ipynb, nbs/docs/use-cases/4_intermittent_demand.ipynb, nbs/docs/use-cases/5_what_if_pricing_scenarios_in_retail.ipynb
- Adds Azure callouts after instantiating NixtlaClient and after calling forecast / cross-validation / detect_anomalies
=> [DOC] Add azure callouts to use cases

nbs/docs/use-cases/2_bitcoin_price_prediction.ipynb
Minor corrections to the text that specify how the model works and its limitations.
=> Minor correction to tutorial

nbs/nixtla_client.ipynb, nixtla/nixtla_client.py
Addresses issue https://github.com/Nixtla/nixtla/issues/424.
The current implementation of cross_validation restricts historical data even when finetune_steps is not zero. This restriction causes an UnprocessableEntityError when fine-tuning is used in cross-validation. 
For instance, the following code using web traffic sample data generates this error:
```
cv_df = nixtla_client.cross_validation(
df,
h=7,
step_size = 7,
n_windows=1,
time_col='date',
target_col='users',
id_col = 'unique_id',
freq='D',
finetune_steps = 10
)
UnprocessableEntityError: status_code: 422, body: detail=None requestID='C2T6854CVQ' details='request had an error' support='If you have questions or need support, please email ops@nixtla.io' data={'detail': 'Minimum number of samples by id required for finetuning is 29, …
```
=> fix: removed data input restriction during cross validation finetune

nbs/docs/getting-started/1_introduction.ipynb
Right now, it says that we can use a custom loss function. That may lead our users to think that they can define their own loss function, when in reality, they can choose from a defined list.
=> [DOC] - Rephrase the sentence for specific loss function

.github/workflows/deploy-readme.yaml, setup.py
The [action is failing](https://github.com/Nixtla/nixtla/actions/runs/10255664075/job/28373067923#step:6:13) because nbdev isn't being installed
=> ci: install dev requirements in deploy-readme action

.github/workflows/build-docs.yaml, .github/workflows/deploy-readme.yaml
This PR modifies the github workflows to create docs on release OR on explicit workflow_dispatch. 
The benefit is that we can push doc PRs to main whilst the features these docs describe aren't necessarily included in the release yet. Basically, this syncs our docs with our releases. 
On-demand doc fixing (when a PR is merged to main) can always still be realized by manually triggering the necessary workflows.
=> [FIX] Create docs on release not on push to main

CONTRIBUTING.md, nbs/docs/getting-started/5_faq.ipynb
- Fixes wrong pricing links in FAQ
- Updates contributing with how to handle linking to files.
=> [FIX] Pricing links incorrect

nbs/src/nixtla_client.ipynb, nixtla/nixtla_client.py
Updates the `validate_api_key` method to perform a `GET /validate_api_key` instead of `POST /validate_token`, since we don't send any data.
Also updates the definition of the method to include a docstring and log the endpoint response.
=> enh: update validate_api_key to use GET request

timegpt-docs/introduction/about_timegpt.mdx
Adds the closing `</Steps>` tag to render the about page correctly.
=> FIX: Add closing steps tag
