.gitignore, Makefile, iac/terraform/aws/.terraform.lock.hcl, iac/terraform/aws/main.tf, iac/terraform/aws/modules/apigateway/main.tf, iac/terraform/aws/modules/apigateway/outputs.tf, iac/terraform/aws/modules/ecr/docker_images.sh, iac/terraform/aws/modules/ecr/main.tf, iac/terraform/aws/modules/ecr/outputs.tf, iac/terraform/aws/modules/iam/main.tf, iac/terraform/aws/modules/iam/output.tf, iac/terraform/aws/modules/s3/.terraform.lock.hcl, iac/terraform/aws/modules/s3/api_lambda.sh, iac/terraform/aws/modules/s3/main.tf, iac/terraform/aws/modules/s3/outputs.tf, iac/terraform/aws/modules/tsbenchmarks/main.tf, iac/terraform/aws/modules/tsbenchmarks/output.tf, iac/terraform/aws/modules/tsfeatures/main.tf, iac/terraform/aws/modules/tsfeatures/output.tf, iac/terraform/aws/modules/tsforecast/main.tf, iac/terraform/aws/modules/tsforecast/output.tf, iac/terraform/aws/modules/tspreprocess/main.tf, iac/terraform/aws/modules/tspreprocess/output.tf, iac/terraform/aws/outputs.tf, iac/terraform/aws/provisioner.tf, iac/terraform/aws/variables.tf
- s3
- ecr
- iam
- tsbenchmarks
- tsfeatures
- tsforecast
- tspreprocess
=> Create terraform iac

README.md
Line 32, col 76, deap -> deep
(pequeña contribución, algo es algo dicen por acá)
=> fix *one* letter typo on README

.fernignore
`.fernignore` tells Fern which files not to touch!
=> :herb: Add `.fernignore`

.github/workflows/deploy_readme.yaml, action_files/create_readme_docs.sh, action_files/modify_markdown.py
This PR adds the current documentation to our README page.
=> [FEAT] Deploy docs to README

action_files/create_readme_docs.sh, action_files/modify_markdown.py
- Remove break lines inside text paragraphs.
- Order slug by number.
=> [FEAT] Improve readme docs

nbs/docs/getting-started/1_getting_started_short.ipynb
There was a missing end of some callout blocks.
=> [FIX] Add end of callout block

CONTRIBUTING.md, nbs/mint.json
=> Add CONTRIBUTING.md and mint.json

nbs/mint.json
Keeping `nbs/sidebar.yaml` for dev purposes.
=> docs: add faqs to mintlify index

environment.yml, nbs/timegpt.ipynb, nixtlats/timegpt.py, setup.py
Before this PR, adding `date_features` to series with different endings resulted in an error.
The error was replicated using a test.
=> fix: solve problem with duplicated dates

.github/workflows/lint.yaml, .pre-commit-config.yaml, CONTRIBUTING.md, nbs/docs/tutorials/5_finetuning.ipynb, nixtlats/distributed/timegpt.py, nixtlats/timegpt.py, setup.py
Adds pre-commit to export and clean the notebooks as well as the lint task to ensure that the pre-commit hooks were executed correctly.
=> add pre-commit

nbs/mint.json
- Add tutorial on setting up the token for TimeGPT
- Add tutorial on specifying a loss function for fine-tuning
- Add tutorial on long-horizon forecasting
=> FEAT - Add new sections to documentation

experiments/amazon-chronos/README.md, experiments/amazon-chronos/environment.yml, experiments/amazon-chronos/src/amazon_chronos/forecaster.py, experiments/amazon-chronos/src/amazon_chronos/pipeline.py, experiments/amazon-chronos/src/main.py, experiments/amazon-chronos/src/statsforecast_pipeline.py, experiments/amazon-chronos/src/utils.py
- feat: add amazon chronos experiment
- fix: add table
=> feat: add amazon chronos benchmark

.fernignore
=> fix: add correct fernignore file

nbs/docs/getting-started/4_data_requirements.ipynb, nbs/docs/getting-started/5_faq.ipynb
Adds minimum data requirements to tutorial of the same name and FAQ.
=> [Hotfix] Minimum data requirements

experiments/foundation-time-series-arena/README.md
Added note to the readme while we review the PR from Amazon's team.
=> fix: note on chronos pr

README.md
There seems to be a chatGPT sentence remaining in the README.md :).
=> Removed a chatGPT (?) sentence in README.md

fern/openapi/timegpt.json
=> Update openapi json file

nbs/docs/deployment/2_azure_ai.ipynb, nbs/docs/getting-started/5_faq.ipynb
Updated information in the docs for 
* API key troubleshooting
* Fees
* Taking off the 'coming soon' on Azure
=> updating FAQ for fee information and Azure being available

README.md
=> docs(readme): getting started

.github/workflows/models-performance.yaml, action_files/comment_file.py
Creates only one "Experiment Results" comment per PR. If a comment already exists then it's edited with the most recent push.
=> feat: create single experiment results comment in PRs

.github/workflows/ci.yaml, nixtla/__init__.py, settings.ini, setup.py
Restores `settings.ini` to be the source of the package configuration, e.g. name, dependencies, version, etc.
=> enh: use configuration from settings.ini

.github/workflows/ci.yaml, settings.ini
* fixes [ipython](https://github.com/AnswerDotAI/nbdev/issues/1501) and [another issue](https://github.com/Nixtla/nixtla/actions/runs/13662905377/job/38197938562) with installation in Windows.
=> fix: for test failure on windows 3.9

.github/workflows/build-docs.yaml, .github/workflows/deploy-readme.yaml
The PR tries to fix to failing `build-docs` workflow and building readme from #665
=> Failing docs ci
